### ISSUE TITLE
Unit test file autocompletion

### ISSUE THREAD

**Issue by eidellev** [sublimelsp/LSP-typescript#21]
Hi and thanks for making this.

For some reason, LSP doesn't seem to be working for test files(`.spec.ts`, `.test.ts`).
I'm probably configuring something wrong but can't figure it out.

**Comment by rchl** [comment]
Does the server start for those files (do you see LSP-typescript in the status bar)?

If it does start then do you see any issues in the diagnostics panel (`LSP: Toggle Diagnostics Panel` from command palette)?

If there are issues then probably you should address those first.

Otherwise, maybe create a simple repo that reproduces.

**Comment by eidellev** [comment]
Thank you for your reply. It looks like it is an issue with the syntax.
By default sublime text sets the syntax to UnitTest(TypeScript) on all my `.spec.ts` files. 
As soon as I change the syntax manually LSP springs to life
