### ISSUE TITLE
In need of dep updates, missing `using`

### ISSUE THREAD

**Issue by brian6932** [sublimelsp/LSP-typescript#221]
Currently doesn't support the `using` keyword
The current `typescript` version says `Unexpected keyword or identifier`

**Comment by rchl** [comment]
The bundled version of Typescript is at 5.2.2 which supports `using`.

If your project has older version of Typescript then that could be the problem because by default this server uses Typescript version that is installed in the project or globally in the system and only then fall-backs to using bundled version.

The used Typescript version is logged in LSP logs of your editor.

**Comment by brian6932** [comment]
I'm talking about the use of `lsp-ts` in a javascript project, without ts installed at all, it can only use `lsp-ts`'s install(?)

**Comment by Serega124** [comment]
> The bundled version of Typescript is at 5.2.2 which supports `using`.

PR #220 is not merged yet, so the bundled version of Typescript is 5.0.4

**Comment by rchl** [comment]
Right. I confused this issue as being reported in typescript-language-server instead

**Comment by rchl** [comment]
Published new version with typescript update: https://github.com/sublimelsp/LSP-typescript/releases/tag/v2.5.0
