### ISSUE TITLE
Autocomplete imports as you type?

### ISSUE THREAD

**Issue by Jarred-Sumner** [sublimelsp/LSP-typescript#46]
Currently, LSP will show modules from other files, but it won't import them when you press enter.
![image](https://user-images.githubusercontent.com/709451/109221902-718b6200-776e-11eb-9381-faec74c142a7.png)

If you click "code actions" it will offer to add the import for you.
![image](https://user-images.githubusercontent.com/709451/109221752-689a9080-776e-11eb-84d0-9b2e132a9e2e.png)

With Visual Studio Code, the experience looks like this:
![image](https://user-images.githubusercontent.com/709451/109222749-a697b480-776e-11eb-91c2-b791a77a955a.png)

When I press enter, it inserts the import at the top of the file:
![image](https://user-images.githubusercontent.com/709451/109222866-b616fd80-776e-11eb-8e8b-d0d425aca0d6.png)

Is there a way to get LSP-typescript to behave similarly to Visual Studio Code on this? Visual Studio Code's way is more productive

**Comment by rchl** [comment]
It does not support that feature.

You could report it at https://github.com/theia-ide/typescript-language-server if it isn't already but the chances of it being done are pretty slim.

The good news is that MS should come up with an official server soonish that will hopefully support that and more.

**Comment by predragnikolic** [comment]
Thanks for opening up this issue. 
In short, yes it is possible.
   
For a long time I thought that this was a language server issue(turned out to be a LSP client bug) because the spec said:

> By default the request can only delay the computation of the detail and documentation properties. 

But now I read the spec and the next sentence is:

> Since 3.16.0 the client can signal that it can resolve more properties lazily. This is done using the completionItem#resolveSupport client capability which lists all properties that can be filled in during a ‘completionItem/resolve’ request. All other properties (usually sortText, filterText, insertText and textEdit) must be provided in the textDocument/completion response and must not be changed during resolve.


The theia typescirpt language server will send back `additionalTextEdits` but only after the completion item is resolved.

LSP for ST3 used to apply additional text edits only after resolving completion items,
but I guess that was changed because some servers didn't support resoling completion items (If i recall correctly, those additional edits didn't get applied in that case, but I am not sure now).

So now(LSP in ST4) we apply additional text edits before resolving completion items, 
which is also not ideal, because some servers will send `additionalTextEdits` only after the completion item is resolved.

**Comment by rchl** [comment]
Good point but in this case it seems like we are doing the right thing. The spec says:

> By default the request can only delay the computation of the detail and documentation properties. Since 3.16.0 the client can signal that it can resolve more properties lazily. This is done using the completionItem#resolveSupport client capability which lists all properties that can be filled in during a ‘completionItem/resolve’ request. All other properties (usually sortText, filterText, insertText and textEdit) must be provided in the textDocument/completion response and must not be changed during resolve.

And this server doesn't have the `resolveSupport` property on the `completionItem` capability.

**Comment by rwols** [comment]
Yep, theia-ide/typescript-language-server does not respect client capabilities. cc @DonnieWest

**Comment by DonnieWest** [comment]
Off the top of my head, probably the biggest blocker here is simply updating `theia-ide/typescript-language-server` to the latest spec version. Last I looked into it, it was a bit hairy to upgrade the required libraries. It's something I'll add to my TODO list
