### ISSUE TITLE
[Question] Complete function calls setting

### ISSUE THREAD

**Issue by ivanddm** [sublimelsp/LSP-typescript#74]
Hi,

I'm wondering if the settings (available for example in VSCode or Coc-tsserver for vim) for completion of function calls (i.e., complete functions with their parameter signatures) are available here for Sublime as well. I tried adding the corresponding settings in LSP-Typescript settings without luck:

```
{
  "settings": {
    "javascript.suggest.completeFunctionCalls": true,
    "typescript.suggest.completeFunctionCalls": true,
  }
}
```

Thanks in advance!

**Comment by rchl** [comment]
As far as I can see the default behavior of this server should match the behavior of Coc-tsserver with this setting enabled.

The coc-tsserver code looks like this:

```js
  let insertTextFormat = (
    context.enableCallCompletions &&
    (kind === CompletionItemKind.Function ||
      kind === CompletionItemKind.Method)
  ) ? InsertTextFormat.Snippet : InsertTextFormat.PlainText
```

while this server's code looks like this:

```js
    if (item.kind === lsp.CompletionItemKind.Function || item.kind === lsp.CompletionItemKind.Method) {
        item.insertTextFormat = lsp.InsertTextFormat.Snippet;
    }
```

So in both cases the `insertTextFormat` is set to `Snippet`.

What specificially do you see working differently with this server?

**Comment by ivanddm** [comment]
These are some examples of function signature completion of what I get in either Coc-tsserver, and VScode:

**Coc-tsserver**:

https://user-images.githubusercontent.com/20104703/128695491-d6fd92af-b187-4920-9d5c-ef58c2d2b150.mp4




**VSCode**:

https://user-images.githubusercontent.com/20104703/128695267-bb30f52a-60d6-46f3-8bb1-c36073034eee.mp4




**ST4**: I'm not getting completion of function signature when I trigger the selection (`listen` in this case) the way I do with Coc or VSCode

https://user-images.githubusercontent.com/20104703/128695288-eac9f7bf-c280-4d7e-bafe-8aebf9eeea3c.mp4




I also use lsp-rust-analyzer in ST4 and I do get function signatures completion, so it might not be an issue with my general LSP config:


https://user-images.githubusercontent.com/20104703/128695311-77968813-4692-4fc3-ad9d-0f2114feb07a.mp4

**Comment by rchl** [comment]
OK, I see that there is quite a bit of custom code in coc/vscode to support that so `typescript-language-server` would need to do the same to support that.

**Comment by rchl** [comment]
I'll close this in favor of https://github.com/typescript-language-server/typescript-language-server/issues/198 since this package just relies on that server.

Thanks for explaining how it works in other editors. It helped me with finding the relevant code.

**Comment by ivanddm** [comment]
Sure, thanks a lot for looking into this.

**Comment by rchl** [comment]
I have implemented that locally in the server but noticed that it won't actually work in Sublime's LSP implementation because we don't resolve `insertText` property of the completion before inserting it. The get this to work we'd ideally need https://github.com/sublimehq/sublime_text/issues/3298 to be solved. Alternative solution would be to resolve all completions before inserting but I'm not sure if that would be acceptable...

I guess the third option would be to do the hack for the LSP-typescript only, as much as I and everyone else hates hacks.

**Comment by ivanddm** [comment]
Does this mean that [sublimelsp/LSP-rust-analyzer](https://github.com/sublimelsp/LSP-rust-analyzer) implements a hack of sorts to provide this feature?

**Comment by rchl** [comment]
TS server fills out that extra information during "completion resolve" stage while rust-analyzer might be providing the information initially, without requiring a resolve. In the TS server this is done in additional step because it would be too costly to compute that information initially for all completions. So those can't be directly compared.

**Comment by ivanddm** [comment]
Got it! I guess the most sensible solution would be to wait for #3298 to be resolved. Thanks again!
